### ISSUE TITLE
LoadError has occurred when executing RSpec with Ruby 3.2.1

### ISSUE THREAD

**Issue by urimaro** [joker1007/rspec-power_assert#10]
### How to reproduce

1. Clone the following repository  
    https://github.com/urimaro/rspec-power_assert-sample
1. `bundle install`
1. `bundle exec rspec`

### Behavior

The following messages were shown.

```
> bundle exec rspec                                                                                                                                                                                               (main)

An error occurred while loading spec_helper. - Did you mean?
                    rspec ./spec/spec_helper.rb

Failure/Error: require 'rspec-power_assert'

LoadError:
  Fully compatible TracePoint API required
# ./vendor/bundle/ruby/3.2.0/gems/power_assert-1.1.7/lib/power_assert.rb:17:in `rescue in <top (required)>'
# ./vendor/bundle/ruby/3.2.0/gems/power_assert-1.1.7/lib/power_assert.rb:5:in `<top (required)>'
# ./vendor/bundle/ruby/3.2.0/gems/rspec-power_assert-1.1.0/lib/rspec/power_assert.rb:3:in `<top (required)>'
# ./vendor/bundle/ruby/3.2.0/gems/rspec-power_assert-1.1.0/lib/rspec-power_assert.rb:1:in `<top (required)>'
# ./spec/spec_helper.rb:17:in `<top (required)>'
# ------------------
# --- Caused by: ---
# RuntimeError:
#   ./vendor/bundle/ruby/3.2.0/gems/power_assert-1.1.7/lib/power_assert.rb:11:in `block in <top (required)>'
No examples found.


Finished in 0.00003 seconds (files took 0.08778 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

In the environment with Ruby 3.1.3, this error doesn't occur.

### System configuration

- Ruby 3.2.1
- Bundler 2.4.7

**Comment by joker1007** [comment]
Thank you for reporting!
I fixed by https://github.com/joker1007/rspec-power_assert/pull/11 and released a new version.
